// packages/core/templates/react/Badge.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
	/** Badge variant */
	variant?: 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'info';
	/** Badge size */
	size?: 'sm' | 'lg';
}

export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
	({ variant = 'primary', size, children, ...rest }, ref) => {
		return (
			<span ref={ref} s-badge={variant} s-size={size} {...rest}>
				{children}
			</span>
		);
	}
);

Badge.displayName = 'Badge';

// packages/core/templates/vue/Badge.vue
<script setup lang="ts">
/**
 * Badge Component
 *
 * @example
 * <Badge>Default</Badge>
 * <Badge variant="success">Success</Badge>
 * <Badge variant="danger" size="sm">Small Danger</Badge>
 */

export interface BadgeProps {
	/** Badge variant */
	variant?: 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'info';
	/** Badge size */
	size?: 'sm' | 'lg';
}

withDefaults(defineProps<BadgeProps>(), {
	variant: 'primary',
});
</script>

<template>
	<span :s-badge="variant" :s-size="size">
		<slot />
	</span>
</template>
