// packages/core/templates/react/Input.tsx
import { forwardRef, type InputHTMLAttributes } from 'react';

export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> {
	/** Input size */
	size?: 'sm' | 'lg';
	/** Error state */
	error?: boolean;
}

export const Input = forwardRef<HTMLInputElement, InputProps>(
	({ size, error = false, type = 'text', ...rest }, ref) => {
		return (
			<input
				ref={ref}
				s-input=""
				s-size={size}
				aria-invalid={error || undefined}
				type={type}
				{...rest}
			/>
		);
	}
);

Input.displayName = 'Input';

// packages/core/templates/vue/Input.vue
<script setup lang="ts">
/**
 * Input Component
 *
 * @example
 * <Input placeholder="Enter text..." />
 * <Input type="email" size="lg" />
 * <Input error />
 */

export interface InputProps {
	/** Input size (omit for default medium size) */
	size?: 'sm' | 'lg';
	/** Input type */
	type?: string;
	/** Error state */
	error?: boolean;
	/** Model value for v-model */
	modelValue?: string;
}

withDefaults(defineProps<InputProps>(), {
	type: 'text',
	error: false,
});

const emit = defineEmits<{
	'update:modelValue': [value: string];
}>();

function handleInput(event: Event) {
	emit('update:modelValue', (event.target as HTMLInputElement).value);
}
</script>

<template>
	<input s-input :s-size="size" :type="type" :aria-invalid="error || undefined" :value="modelValue"
		@input="handleInput" />
</template>
