// packages/core/templates/react/Modal.tsx
import { type DialogHTMLAttributes, forwardRef } from 'react';

export interface ModalProps extends DialogHTMLAttributes<HTMLDialogElement> {
	/** Modal size */
	size?: 'sm' | 'lg' | 'xl' | 'full';
	/** Modal position */
	position?: 'center' | 'top' | 'bottom' | 'left' | 'right';
}

export const Modal = forwardRef<HTMLDialogElement, ModalProps>(
	({ size, position, children, ...rest }, ref) => {
		return (
			<dialog ref={ref} s-modal="" s-size={size} s-position={position} {...rest}>
				{children}
			</dialog>
		);
	}
);

Modal.displayName = 'Modal';

// packages/core/templates/vue/Modal.vue
<script setup lang="ts">
import { ref, watch } from 'vue';

/**
 * Modal Component
 *
 * @example
 * <Modal v-model:open="isOpen">
 *   <div s-modal-header>Title</div>
 *   <div s-modal-body>Content</div>
 * </Modal>
 */

export interface ModalProps {
	/** Modal size */
	size?: 'sm' | 'lg' | 'xl' | 'full';
	/** Modal position */
	position?: 'center' | 'top' | 'bottom' | 'left' | 'right';
	/** Control modal open state */
	open?: boolean;
}

const props = defineProps<ModalProps>();

const emit = defineEmits<{
	'update:open': [value: boolean];
}>();

const dialogRef = ref<HTMLDialogElement | null>(null);

watch(
	() => props.open,
	(isOpen) => {
		if (isOpen) {
			dialogRef.value?.showModal();
		} else {
			dialogRef.value?.close();
		}
	}
);

function handleClose() {
	emit('update:open', false);
}
</script>

<template>
	<dialog ref="dialogRef" s-modal="" :s-size="size" :s-position="position" @close="handleClose">
		<slot />
	</dialog>
</template>
