// packages/core/templates/react/Tooltip.tsx
import { forwardRef, type HTMLAttributes } from 'react';

export interface TooltipProps extends HTMLAttributes<HTMLSpanElement> {
	/** Tooltip text content */
	text: string;
	/** Tooltip position */
	position?: 'top' | 'bottom' | 'left' | 'right';
}

export const Tooltip = forwardRef<HTMLSpanElement, TooltipProps>(
	({ text, position, children, ...rest }, ref) => {
		return (
			<span ref={ref} s-tooltip={position} s-tooltip-text={text} title={text} {...rest}>
				{children}
			</span>
		);
	}
);

Tooltip.displayName = 'Tooltip';

// packages/core/templates/vue/Tooltip.vue
<script setup lang="ts">
/**
 * Tooltip Component
 *
 * @example
 * <Tooltip text="Helpful info">Hover me</Tooltip>
 * <Tooltip text="Bottom tooltip" position="bottom">Hover me</Tooltip>
 */

export interface TooltipProps {
	/** Tooltip text content */
	text: string;
	/** Tooltip position */
	position?: 'top' | 'bottom' | 'left' | 'right';
}

defineProps<TooltipProps>();
</script>

<template>
	<span :s-tooltip="position" :s-tooltip-text="text" :title="text">
		<slot />
	</span>
</template>
