// packages/core/templates/vue/Menu.vue
<script setup lang="ts">
import { onMounted, computed } from 'vue';

/**
 * Menu Component
 *
 * Requires either aria-label or aria-labelledby for accessibility.
 *
 * @example
 * <Menu aria-label="Actions menu">
 *   <a s-menu-item href="#">Item 1</a>
 *   <a s-menu-item href="#">Item 2</a>
 * </Menu>
 */

export interface MenuProps {
	/** Menu size */
	size?: 'sm' | 'lg';
	/** Accessible label for the menu */
	ariaLabel?: string;
	/** ID of element that labels the menu */
	ariaLabelledby?: string;
}

const props = defineProps<MenuProps>();

const hasAccessibleName = computed(() => props.ariaLabel || props.ariaLabelledby);

onMounted(() => {
	if (!hasAccessibleName.value) {
		console.warn('[Menu] Accessibility warning: Menu requires either aria-label or aria-labelledby');
	}
});
</script>

<template>
	<div v-if="hasAccessibleName" s-menu :s-size="size" role="menu" :aria-label="ariaLabel"
		:aria-labelledby="ariaLabelledby">
		<slot />
	</div>
</template>

// packages/core/templates/react/Menu.tsx
import { forwardRef, type HTMLAttributes, useEffect } from 'react';

export interface MenuProps extends HTMLAttributes<HTMLDivElement> {
	/** Menu size */
	size?: 'sm' | 'lg';
}

export const Menu = forwardRef<HTMLDivElement, MenuProps>(
	(
		{ size, children, 'aria-label': ariaLabel, 'aria-labelledby': ariaLabelledby, ...rest },
		ref
	) => {
		useEffect(() => {
			if (!ariaLabel && !ariaLabelledby) {
				console.warn(
					'[Menu] Accessibility warning: Menu requires either aria-label or aria-labelledby'
				);
			}
		}, [ariaLabel, ariaLabelledby]);

		if (!ariaLabel && !ariaLabelledby) {
			return null;
		}

		return (
			<div
				ref={ref}
				s-menu
				s-size={size}
				role="menu"
				aria-label={ariaLabel}
				aria-labelledby={ariaLabelledby}
				{...rest}
			>
				{children}
			</div>
		);
	}
);

Menu.displayName = 'Menu';
