// packages/core/templates/vue/SkipLink.vue
<script setup lang="ts">
/**
 * Skip Link Component
 *
 * @example
 * <SkipLink />
 * <SkipLink target="#content">Skip to content</SkipLink>
 */

export interface SkipLinkProps {
	/** Target element ID to skip to */
	target?: string;
}

withDefaults(defineProps<SkipLinkProps>(), {
	target: '#main',
});
</script>

<template>
	<a s-skip-link="" :href="target">
		<slot>Skip to main content</slot>
	</a>
</template>

// packages/core/templates/react/SkipLink.tsx
import { type AnchorHTMLAttributes, forwardRef } from 'react';

export interface SkipLinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
	/** Target element ID to skip to */
	target?: string;
}

export const SkipLink = forwardRef<HTMLAnchorElement, SkipLinkProps>(
	({ target = '#main', children = 'Skip to main content', ...rest }, ref) => {
		return (
			<a ref={ref} s-skip-link="" href={target} {...rest}>
				{children}
			</a>
		);
	}
);

SkipLink.displayName = 'SkipLink';
